path: /export/home/lcerrone/Datasets/TUM_Ovules_Dataset/Ovules_test_final/unet_ds2x_bce_gcr_all
preprocessing:
  factor:
  - 1.0
  - 1.0
  - 1.0
  filter:
    filter_param: 1.0
    state: false
    type: gaussian
  order: 2
  save_directory: preprocessing
  state: false
segmentation:
  multicut_beta: 0.5
  name: MultiCut
  post_minsize: 50
  postprocessing:
    factor:
    - 1
    - 1
    - 1
    order: 0
    state: false
    tiff: false
  run_ws: true
  save_directory: MultiCut
  state: true
  ws_2D: false
  ws_minsize: 50
  ws_sigma: 2.0
  ws_threshold: 0.5
  ws_w_sigma: 0
unet_prediction:
  device: cuda
  model_name: unet_ds2x_bce_gcr_all
  model_update: false
  patch:
  - 128
  - 224
  - 224
  postprocessing:
    factor:
    - 1
    - 1
    - 1
    order: 2
    state: false
    tiff: false
  state: false
  stride:
  - 64
  - 128
  - 128
  version: best
