# Contains the path to the directory or file to process
path: "/export/home/lcerrone/Datasets/TUM_Ovules_Dataset/Ovules_test_final/"

preprocessing:
  # enable/disable preprocessing
  state: False
  # create a new sub folder where all results will be stored
  save_directory: "preprocessing"
  # rescaling the volume is essential for the generalization of the networks. The rescaling factor can be computed as the resolution
  # of the volume at hand divided by the resolution of the dataset used in training. Be careful, if the difference is too large check for a different model.
  factor: [1.0, 1.0, 1.0]
  # the order of the spline interpolation
  order: 2
  # optional: perform Gaussian smoothing or median filtering on the input.
  filter:
    # enable/disable filtering
    state: False
    # Accepted values: 'gaussian'/'median'
    type: gaussian
    # sigma (gaussian) or disc radius (median)
    filter_param: 1.0

unet_prediction:
  # enable/disable UNet prediction
  state: True
  # Trained model name, more info on available models and custom models in the README
  model_name: "unet_ds2x_dice_gcr"
  # If a CUDA capable gpu is available and corrected setup use "cuda", if not you can use "cpu" for cpu only inference (slower)
  device: "cuda"
  # patch size given to the network (adapt to fit in your GPU mem)
  patch: [128, 224, 224]
  # stride between patches (make sure the the patches overlap in order to get smoother prediction maps)
  stride: [64, 128, 128]
  # "best" refers to best performing on the val set (recommended), alternatively "last" refers to the last version before interruption
  version: best
  # If "True" forces downloading networks for the online repos
  model_update: False

  postprocessing:
    state: False
    tiff: False
    factor: [1, 1, 1]
    order: 2


segmentation:
  # enable/disable segmentation
  state: False
  # Name of the algorithm to use for inferences
  name: "MultiCut"
  # Segmentation specific parameters here
  # balance under-/over-segmentation; 0 - aim for undersegmentation, 1 - aim for oversegmentation
  multicut_beta: 0.5
  # directory where to save the results
  save_directory: "MultiCut"
  # enable/disable watershed
  run_ws: True
  # use 2D instead of 3D watershed
  ws_2D: True
  # probability maps threshold
  ws_threshold: 0.5
  # minimum size of the superpixels
  ws_minsize: 50
  # sigma for the gaussian smoothing of the distance transform
  ws_sigma: 2.0
  ws_w_sigma: 0
  post_minsize: 50
  postprocessing:
    state: False
    tiff: False
    factor: [1, 1, 1]
    order: 0

